name: Sleep1

on:
  push:
    branches:
      - master
      - release/*
  # pull_request:
  #   branches:
  #     - master
  # schedule:
  #   - cron: 0 2 * * 1-5

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: sleep
      run: |
          echo "sleep 15"
          sleep 15
          echo "sleep 30"
          sleep 30
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
